# Generated by Django 4.2.3 on 2024-12-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("video_file", models.FileField(upload_to="videos/")),
                ("start_timestamp", models.DateTimeField()),
                ("end_timestamp", models.DateTimeField()),
            ],
        ),
    ]
